version: '3.3'

services:
  db:
    image: mysql
    restart: always

    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      - '3306:3306'

    expose:
      - '3306'

    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: